File data/test1_test2/nouns/csv/k.csv write successfully!
File data/test1_test2/nouns/csv/b.csv write successfully!
File data/test1_test2/nouns/csv/m.csv write successfully!
Error when call API: The server had an error while processing your request. Sorry about that!
File data/test1_test2/nouns/csv/c.csv write successfully!
Error when call API: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error when call API: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f520225b0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Error when call API: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
